### ISSUE TITLE
PathsIter missing next method

### ISSUE THREAD

**Issue by svenil** [zhuyifei1999/guppy3#2]
When doing the following we get an exception. It seems Python3 needs the next method for iterator not the "_ next _" method. When I define the next method in PathsIter in guppy/heapy/Path.py it works. I have tested in the Guppy3-3.0.3 release as well as latest trunk as of today 10 sep 2019.

Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from guppy import hpy
>>> h=hpy()
>>> hp=h.heap()
>>> hp
Partition of a set of 34117 objects. Total size = 2248255 bytes.
 Index  Count   %     Size   % Cumulative  % Kind (class / dict of class)
     0   9003  26   595755  26    595755  26 str
     1   8437  25   303296  13    899051  40 tuple
     2   4369  13   229084  10   1128135  50 bytes
     3   2187   6   183708   8   1311843  58 types.CodeType
     4    402   1   177108   8   1488951  66 type
     5   2141   6   145588   6   1634539  73 function
     6    402   1   120156   5   1754695  78 dict of type
     7     93   0    82324   4   1837019  82 dict of module
     8    189   1    70004   3   1907023  85 dict (no owner)
     9    396   1    44352   2   1951375  87 set
<93 more rows. Type e.g. '_.more' to view.>
>>> hp.sp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/guppy3-3.0.3-py3.6-linux-i686.egg/guppy/heapy/Path.py", line 330, in __repr__
    self.pp(output=f)
  File "/usr/local/lib/python3.6/dist-packages/guppy3-3.0.3-py3.6-linux-i686.egg/guppy/heapy/Path.py", line 412, in pp
    self.more(start, output=output)
  File "/usr/local/lib/python3.6/dist-packages/guppy3-3.0.3-py3.6-linux-i686.egg/guppy/heapy/Path.py", line 258, in __call__
    self.printiter(it, output)
  File "/usr/local/lib/python3.6/dist-packages/guppy3-3.0.3-py3.6-linux-i686.egg/guppy/heapy/Path.py", line 433, in printiter
    it.next().pp(output=output)
AttributeError: 'PathsIter' object has no attribute 'next'

**Comment by zhuyifei1999** [comment]
Formatted:
```Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from guppy import hpy
>>> h=hpy()
>>> hp=h.heap()
>>> hp
Partition of a set of 34117 objects. Total size = 2248255 bytes.
 Index  Count   %     Size   % Cumulative  % Kind (class / dict of class)
     0   9003  26   595755  26    595755  26 str
     1   8437  25   303296  13    899051  40 tuple
     2   4369  13   229084  10   1128135  50 bytes
     3   2187   6   183708   8   1311843  58 types.CodeType
     4    402   1   177108   8   1488951  66 type
     5   2141   6   145588   6   1634539  73 function
     6    402   1   120156   5   1754695  78 dict of type
     7     93   0    82324   4   1837019  82 dict of module
     8    189   1    70004   3   1907023  85 dict (no owner)
     9    396   1    44352   2   1951375  87 set
<93 more rows. Type e.g. '_.more' to view.>
>>> hp.sp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/guppy3-3.0.3-py3.6-linux-i686.egg/guppy/heapy/Path.py", line 330, in __repr__
    self.pp(output=f)
  File "/usr/local/lib/python3.6/dist-packages/guppy3-3.0.3-py3.6-linux-i686.egg/guppy/heapy/Path.py", line 412, in pp
    self.more(start, output=output)
  File "/usr/local/lib/python3.6/dist-packages/guppy3-3.0.3-py3.6-linux-i686.egg/guppy/heapy/Path.py", line 258, in __call__
    self.printiter(it, output)
  File "/usr/local/lib/python3.6/dist-packages/guppy3-3.0.3-py3.6-linux-i686.egg/guppy/heapy/Path.py", line 433, in printiter
    it.next().pp(output=output)
AttributeError: 'PathsIter' object has no attribute 'next'
```

Fixed. Thanks for reporting.
