### ISSUE TITLE
CPython tracer / profiler hooks completely break tests

### ISSUE THREAD

**Issue by zhuyifei1999** [zhuyifei1999/guppy3#3]
To reproduce, with just a dummy tracer:
```
$ python -c 'trace = lambda frame, event, arg: trace; __import__("sys").settrace(trace); __import__("guppy").hpy().test()'
[...]
imported: guppy.heapy.test.test_Classifiers
test_base_classes (guppy.heapy.test.test_Classifiers.BaseCase) ... GC hook object was referred to from somebody!
ok
test_fancy_list_args (guppy.heapy.test.test_Classifiers.BaseCase) ... GC hook object was referred to from somebody!
ok
test_fancy_type_conversions (guppy.heapy.test.test_Classifiers.BaseCase) ... GC hook object was referred to from somebody!
ok
test_invalid_operations (guppy.heapy.test.test_Classifiers.BaseCase) ... GC hook object was referred to from somebody!
ok
test_minmax (guppy.heapy.test.test_Classifiers.BaseCase) ... GC hook object was referred to from somebody!
ok

----------------------------------------------------------------------
Ran 5 tests in 0.182s

OK
test_classification (guppy.heapy.test.test_Classifiers.ClassificationCase) ... GC hook object was referred to from somebody!
ok
test_selection (guppy.heapy.test.test_Classifiers.ClassificationCase) ... GC hook object was referred to from somebody!
GC hook object was referred to from somebody!
GC hook object was referred to from somebody!
GC hook object was referred to from somebody!
GC hook object was referred to from somebody!
GC hook object was referred to from somebody!
ok

----------------------------------------------------------------------
Ran 2 tests in 19.371s

OK
test_laws (guppy.heapy.test.test_Classifiers.LawsCase) ... GC hook object was referred to from somebody!
ok

----------------------------------------------------------------------
Ran 1 test in 0.872s

OK
test_rendering (guppy.heapy.test.test_Classifiers.RenderCase) ... GC hook object was referred to from somebody!
ok

----------------------------------------------------------------------
Ran 1 test in 0.190s

OK
test_1 (guppy.heapy.test.test_Classifiers.SpecialCases) ... GC hook object was referred to from somebody!
GC hook object was referred to from somebody!
GC hook object was referred to from somebody!
GC hook object was referred to from somebody!
GC hook object was referred to from somebody!
GC hook object was referred to from somebody!
GC hook object was referred to from somebody!
GC hook object was referred to from somebody!
GC hook object was referred to from somebody!
GC hook object was referred to from somebody!
GC hook object was referred to from somebody!
GC hook object was referred to from somebody!
GC hook object was referred to from somebody!
GC hook object was referred to from somebody!
GC hook object was referred to from somebody!
GC hook object was referred to from somebody!
GC hook object was referred to from somebody!
ok
test_2 (guppy.heapy.test.test_Classifiers.SpecialCases) ... GC hook object was referred to from somebody!
ok
test_alt_retclaset (guppy.heapy.test.test_Classifiers.SpecialCases) ... GC hook object was referred to from somebody!
ok
test_dictowner (guppy.heapy.test.test_Classifiers.SpecialCases) ... GC hook object was referred to from somebody!
ok
test_retclaset (guppy.heapy.test.test_Classifiers.SpecialCases) ... GC hook object was referred to from somebody!
aseq: Expected: b =  8
Got actually  : a =  22
FAIL
test_via (guppy.heapy.test.test_Classifiers.SpecialCases) ... GC hook object was referred to from somebody!
FAIL

======================================================================
FAIL: test_retclaset (guppy.heapy.test.test_Classifiers.SpecialCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/zhuyifei1999/guppy3/guppy/heapy/test/test_Classifiers.py", line 347, in test_retclaset
    self.aseq(grc(C1), rcC1)        # (A)
  File "/home/zhuyifei1999/guppy3/guppy/heapy/test/support.py", line 249, in aseq
    self.assertTrue(0)
AssertionError: 0 is not true

======================================================================
FAIL: test_via (guppy.heapy.test.test_Classifiers.SpecialCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/zhuyifei1999/guppy3/guppy/heapy/test/test_Classifiers.py", line 425, in test_via
    s.byvia.kind == hp.Via("_.f_locals['v']", "_[('k',)]", "_[('v',)]", '_.keys()[0]'))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 6 tests in 2.720s

FAILED (failures=2)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/zhuyifei1999/guppy3/guppy/heapy/Use.py", line 363, in test
    self._parent.test.test_all.test_main(debug)
  File "/home/zhuyifei1999/guppy3/guppy/heapy/test/test_all.py", line 35, in test_main
    f(debug=debug)
  File "/home/zhuyifei1999/guppy3/guppy/heapy/test/test_Classifiers.py", line 959, in test_main
    support.run_unittest(SpecialCases, debug)
  File "/home/zhuyifei1999/guppy3/guppy/heapy/test/support.py", line 186, in run_unittest
    run_suite(suite, testclass)
  File "/home/zhuyifei1999/guppy3/guppy/heapy/test/support.py", line 176, in run_suite
    raise TestFailed(msg)
guppy.heapy.test.support.TestFailed: errors occurred in guppy.heapy.test.test_Classifiers.SpecialCases
```

The reference chains seem to contain unexpected values.

If the tracer / profiler is completely C then it works fine (try using `profile` and `cProfile` to profile the tests).

@svenil found that this is probably related to the use of [PyFrame_FastToLocalsWithError in call_trampoline](https://github.com/python/cpython/blob/41c57b335330ff48af098d47e379e0f9ba09d233/Python/sysmodule.c#L881), and [test.test_sys.SysModuleTest.test_refcount](https://github.com/python/cpython/blob/8f4ef3b019ce380022018587571b0f970e668de3/Lib/test/test_sys.py#L343) & [test.support.refcount_test](https://github.com/python/cpython/blob/1ac2a83f30312976502fda042db5ce18d10ceec2/Lib/test/support/__init__.py#L1967) may explain the reason.

**Comment by svenil** [comment]
Interesting links to the CPython tests and the test_refcount test in particular which had to use a global instead of a local when testing refcounts.. Global objects don't get more references by PyFrame_FastToLocals.

Maybe a workaround would be to use global objects in Heapy tests and for the GC Hook object but I am not sure if it would have bad consequences or how many changes would be needed. What about multiple Heapy objects...

**Comment by zhuyifei1999** [comment]
Hmm... I want to see if there is a way to clear this reference chain, even if we must use C code.

**Comment by zhuyifei1999** [comment]
I just saw https://bugs.python.org/issue30744...

**Comment by zhuyifei1999** [comment]
The ugly side of this is that, I can't just simply clear these locals dicts. `PyFrame_LocalsToFast` is called with clear set so clearing the dict would effectively clear all locals.

Now I wish [PEP 558](https://www.python.org/dev/peps/pep-0558/) get some real progress.

**Comment by zhuyifei1999** [comment]
Yeah, I'm afraid unless that PEP gets done, assigning to a temporary container is the only way to avoid this extra reference. How about, make Guppy work under a tracer, but don't expect the tests to pass? I mean, people are unlikely going to hit this unless they pdb against guppy test suite.

Btw, why make `_local_clear_hook_handle` a attribute of the glue instead of a container as a local variable? The extra reference from the call_trampoline is only going to affect objects directly referenced by a frame as a local variable.

**Comment by svenil** [comment]
Yes, a local container seems to be a much easier and better way to do it!
And yes, it sounds at least somewhat reasonable to not require the tests to pass when tracing is enabled, unless you need that to find out the reachable code.

**Comment by zhuyifei1999** [comment]
> unless you need that to find out the reachable code.

One could use a tracer written in C to trace this. I was just messing with Python tracers ;)

I think for someone who isn't trying to mess with stuffs, pdb is probably the most likely Python tracer being used, especially that most popular and less complex tracers have a variant written in C, like cProfile vs profile.
