### ISSUE TITLE
TypeError: '<' not supported between instances of 'weakref' and 'weakref'

### ISSUE THREAD

**Issue by pi-no** [zhuyifei1999/guppy3#36]
Hi. I'm trying to execute ">>> x.shpaths" for some x, which results in the following stack trace.

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/pino/projects/krrez_9_venv/lib/python3.9/site-packages/guppy/heapy/OutputHandling.py", line 386, in reprfunc
    return self.printer.get_str_of_top()
  File "/home/pino/projects/krrez_9_venv/lib/python3.9/site-packages/guppy/heapy/OutputHandling.py", line 272, in get_str_of_top
    return self.get_str(self, True)
  File "/home/pino/projects/krrez_9_venv/lib/python3.9/site-packages/guppy/heapy/OutputHandling.py", line 339, in get_str
    return self.mod.View.enter(lambda: f())
  File "/home/pino/projects/krrez_9_venv/lib/python3.9/site-packages/guppy/heapy/View.py", line 256, in enter
    retval = func()
  File "/home/pino/projects/krrez_9_venv/lib/python3.9/site-packages/guppy/heapy/OutputHandling.py", line 339, in <lambda>
    return self.mod.View.enter(lambda: f())
  File "/home/pino/projects/krrez_9_venv/lib/python3.9/site-packages/guppy/heapy/OutputHandling.py", line 307, in f
    nxt = next(it)
  File "/home/pino/projects/krrez_9_venv/lib/python3.9/site-packages/guppy/heapy/OutputHandling.py", line 232, in lines_from
    yield self.line_at(idx)
  File "/home/pino/projects/krrez_9_venv/lib/python3.9/site-packages/guppy/heapy/OutputHandling.py", line 212, in line_at
    li = next(self.line_iter)
  File "/home/pino/projects/krrez_9_venv/lib/python3.9/site-packages/guppy/heapy/Path.py", line 368, in _oh_get_line_iter
    for el in self:
  File "/home/pino/projects/krrez_9_venv/lib/python3.9/site-packages/guppy/heapy/Path.py", line 289, in __iter__
    return self.iter()
  File "/home/pino/projects/krrez_9_venv/lib/python3.9/site-packages/guppy/heapy/Path.py", line 292, in iter
    return PathsIter(self, start, stop)
  File "/home/pino/projects/krrez_9_venv/lib/python3.9/site-packages/guppy/heapy/Path.py", line 176, in __init__
    self.reset(start)
  File "/home/pino/projects/krrez_9_venv/lib/python3.9/site-packages/guppy/heapy/Path.py", line 209, in reset
    sr = self.mod.sortedrels(self.paths.IG, src)
  File "/home/pino/projects/krrez_9_venv/lib/python3.9/site-packages/guppy/heapy/Path.py", line 462, in sortedrels
    t.sort(key=lambda x: x[0])
  File "/home/pino/projects/krrez_9_venv/lib/python3.9/site-packages/guppy/heapy/Path.py", line 94, in __lt__
    return self.r < other.r
TypeError: '<' not supported between instances of 'weakref' and 'weakref'

```

**Comment by zhuyifei1999** [comment]
hmm. Is this how to reproduce this?

```
$ python
Python 3.9.9 (main, Nov 17 2021, 14:19:07) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import weakref
>>> key1 = lambda: None
>>> key2 = lambda: None
>>> obj = object()
>>> dct = {weakref.ref(key1): obj, weakref.ref(key2): obj}
>>> import guppy
>>> iso = guppy.hpy().iso(obj)
>>> del obj
>>> iso.shpaths
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zhuyifei1999/guppy3/guppy/heapy/OutputHandling.py", line 386, in reprfunc
    return self.printer.get_str_of_top()
  File "/home/zhuyifei1999/guppy3/guppy/heapy/OutputHandling.py", line 272, in get_str_of_top
    return self.get_str(self, True)
  File "/home/zhuyifei1999/guppy3/guppy/heapy/OutputHandling.py", line 339, in get_str
    return self.mod.View.enter(lambda: f())
  File "/home/zhuyifei1999/guppy3/guppy/heapy/View.py", line 256, in enter
    retval = func()
  File "/home/zhuyifei1999/guppy3/guppy/heapy/OutputHandling.py", line 339, in <lambda>
    return self.mod.View.enter(lambda: f())
  File "/home/zhuyifei1999/guppy3/guppy/heapy/OutputHandling.py", line 307, in f
    nxt = next(it)
  File "/home/zhuyifei1999/guppy3/guppy/heapy/OutputHandling.py", line 232, in lines_from
    yield self.line_at(idx)
  File "/home/zhuyifei1999/guppy3/guppy/heapy/OutputHandling.py", line 212, in line_at
    li = next(self.line_iter)
  File "/home/zhuyifei1999/guppy3/guppy/heapy/Path.py", line 368, in _oh_get_line_iter
    for el in self:
  File "/home/zhuyifei1999/guppy3/guppy/heapy/Path.py", line 289, in __iter__
    return self.iter()
  File "/home/zhuyifei1999/guppy3/guppy/heapy/Path.py", line 292, in iter
    return PathsIter(self, start, stop)
  File "/home/zhuyifei1999/guppy3/guppy/heapy/Path.py", line 176, in __init__
    self.reset(start)
  File "/home/zhuyifei1999/guppy3/guppy/heapy/Path.py", line 209, in reset
    sr = self.mod.sortedrels(self.paths.IG, src)
  File "/home/zhuyifei1999/guppy3/guppy/heapy/Path.py", line 462, in sortedrels
    t.sort(key=lambda x: x[0])
  File "/home/zhuyifei1999/guppy3/guppy/heapy/Path.py", line 94, in __lt__
    return self.r < other.r
TypeError: '<' not supported between instances of 'weakref' and 'weakref'
```

I think among all the relations, only dict keys can be weakrefs. I guess I could change it so that if a comparison fails, compare its id(). The problem is that in that case, say, id(1) > id('foo') and id(2) < id('foo'), it implies id(2) < id('foo') < id(1), but that would conflict with 1 < 2. I could say compare type(1) and type('foo') when the types are different, and when types are the same, try to compare directly, and if that fails with typeerror, compare id... that should work right?

**Comment by pi-no** [comment]
That's at least how I patched it here, and I think it was okay, but you probably know better what consequences that can have. But maybe it's not worse than crashing. :)

**Comment by zhuyifei1999** [comment]
Yep. 5542d9c5fbee16674194d8318665b5f1914dbb85 should fix it. If dict keys have same-type-but-sometimes-compariable says, say `(None,)` and `(1,)`, it might fail to have total ordering but there's not much I can do about it.

**Comment by pi-no** [comment]
Thanks a lot!
